**Biomedical Software Engineering**

**Prof. Arthur Goldberg**

**Dept. Genetics and Genomic Sciences**

**Spring 1, 2020**

# Advanced Python: Numerical computing with `NumPy`

[`NumPy`](https://docs.scipy.org/doc/numpy/index.html) is a popular numerical computing package in Python. NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. The following examples illustrate its basic functionality.

The [`NumPy` User Guide](https://docs.scipy.org/doc/numpy/user/index.html) provides an introductory overview of `NumPy`. The [`NumPy` Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html) explains `NumPy`'s functionality and supplies simple examples.

Construct arrays:

In [25]:
import numpy as np
example_array = np.array([[1, 2, 3], [4, 5, 6]]) # a 2x3 matrix with elements equal to 1..6
print(example_array)
print(type(example_array)) # the type of numpy arrays is `ndarray`

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [26]:
np.empty((2, 2)) # a 2x2 matrix with each element equal to a randomly selected number

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((2, 2)) # a 2x2 matrix with each element equal to 0.0
np.ones((3, 4)) # a 2x3 matrix with each element equal to 1.0

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((2, 3), 2.0) # a 2x3 matrix with each element equal to 2.0

array([[2., 2., 2.],
       [2., 2., 2.]])

In [5]:
np.array([1, 5]) # from a list; can be made from other iterators

array([1, 5])

Access arrays with indexing & slicing

In [6]:
example_array[0, 0] # row, column

1

In [7]:
example_array[(1, 2)] # can use tuple; n-dimensional array addressed by n-tuple

6

In [8]:
example_array[0, :] # slice first row

array([1, 2, 3])

In [9]:
example_array[:, 1] # slice 2nd column

array([2, 5])

In [28]:
example_array[(1, 2, 3)] # wrong size tuple will raise error

IndexError: ignored

Array properties

In [10]:
example_array.shape # shape; # rows, # columns; generalizes to n-dimensions

(2, 3)

In [11]:
example_array.ndim  # number dimensions

2

In [12]:
example_array.dtype.name  # name of the data type in all cells

'int64'

In [13]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [29]:
# can assign data type on creation
c = np.array([2, 3, 5], dtype=np.float64)
c.dtype

dtype('float64')

Operations on arrays

In [14]:
example_array + 3 # operate on all elements

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
example_array + np.full((2, 3), 2.0)  # matrix addition; note float elements

array([[3., 4., 5.],
       [6., 7., 8.]])

In [16]:
example_array += 1 # supports unary assignment, +=, *=, etc.
example_array

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
example_array.dot(np.array([1, 2, 3])) # matrix multiplication

array([20, 38])

In [18]:
example_array.transpose() # transpose array

array([[2, 5],
       [3, 6],
       [4, 7]])

In [19]:
example_array.transpose().transpose()

array([[2, 3, 4],
       [5, 6, 7]])

In [20]:
np.square(example_array)  # one of many mathematical functions

array([[ 4,  9, 16],
       [25, 36, 49]])

Many other operators

Compare arrays

In [21]:
np.array_equal(example_array, example_array)

True

In [22]:
np.array_equal(example_array, example_array.transpose().transpose())  # transpose inverts itself

True

In [23]:
np.array_equal(example_array, example_array + 1)

False

Data reduction

In [24]:
print(example_array.all()) # determine if all of the values are logically equivalent to `True`
print(example_array.any()) # determine if any of the values are logically equivalent to `True`
print(example_array.sum()) # sum
print(example_array.mean()) # mean
print(example_array.std()) # standard deviation
print(example_array.var()) # variance
print(example_array.min()) # minimum
print(example_array.max()) # maximum

True
True
27
4.5
1.707825127659933
2.9166666666666665
2
7
